//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zapoctova_uloha {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resourcecs_CZ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resourcecs_CZ() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zapoctova_uloha.Resourcecs_CZ", typeof(Resourcecs_CZ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90 sekund.
        /// </summary>
        public static string answer1 {
            get {
                return ResourceManager.GetString("answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srv.Q.
        /// </summary>
        public static string answer10 {
            get {
                return ResourceManager.GetString("answer10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phase.O.
        /// </summary>
        public static string answer11 {
            get {
                return ResourceManager.GetString("answer11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubory YAML spoléhajíci se na správné odsazení.
        /// </summary>
        public static string answer12 {
            get {
                return ResourceManager.GetString("answer12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubory YAML založené na XM.
        /// </summary>
        public static string answer13 {
            get {
                return ResourceManager.GetString("answer13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubory YAML které jsou platné v souboru JSON..
        /// </summary>
        public static string answer14 {
            get {
                return ResourceManager.GetString("answer14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event()..
        /// </summary>
        public static string answer15 {
            get {
                return ResourceManager.GetString("answer15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julia.
        /// </summary>
        public static string answer16 {
            get {
                return ResourceManager.GetString("answer16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java.
        /// </summary>
        public static string answer17 {
            get {
                return ResourceManager.GetString("answer17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript.
        /// </summary>
        public static string answer18 {
            get {
                return ResourceManager.GetString("answer18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přesně jednu.
        /// </summary>
        public static string answer19 {
            get {
                return ResourceManager.GetString("answer19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 sekund.
        /// </summary>
        public static string answer2 {
            get {
                return ResourceManager.GetString("answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přesně tři.
        /// </summary>
        public static string answer20 {
            get {
                return ResourceManager.GetString("answer20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Několik.
        /// </summary>
        public static string answer21 {
            get {
                return ResourceManager.GetString("answer21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10420.
        /// </summary>
        public static string answer22 {
            get {
                return ResourceManager.GetString("answer22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8192.
        /// </summary>
        public static string answer23 {
            get {
                return ResourceManager.GetString("answer23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14200.
        /// </summary>
        public static string answer24 {
            get {
                return ResourceManager.GetString("answer24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw.
        /// </summary>
        public static string answer25 {
            get {
                return ResourceManager.GetString("answer25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emit.
        /// </summary>
        public static string answer26 {
            get {
                return ResourceManager.GetString("answer26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream.
        /// </summary>
        public static string answer27 {
            get {
                return ResourceManager.GetString("answer27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 GB.
        /// </summary>
        public static string answer28 {
            get {
                return ResourceManager.GetString("answer28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2,5 GB.
        /// </summary>
        public static string answer29 {
            get {
                return ResourceManager.GetString("answer29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 sekund.
        /// </summary>
        public static string answer3 {
            get {
                return ResourceManager.GetString("answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,5 GB.
        /// </summary>
        public static string answer30 {
            get {
                return ResourceManager.GetString("answer30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 tisíc požadavků za hodinu pro všechny uživatele.
        /// </summary>
        public static string answer31 {
            get {
                return ResourceManager.GetString("answer31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 tisíc požadavků za hodinu pro všechny uživatele.
        /// </summary>
        public static string answer32 {
            get {
                return ResourceManager.GetString("answer32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 tisíc požadavků za hodinu pro všechny uživatele.
        /// </summary>
        public static string answer33 {
            get {
                return ResourceManager.GetString("answer33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-1.
        /// </summary>
        public static string answer34 {
            get {
                return ResourceManager.GetString("answer34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-n.
        /// </summary>
        public static string answer35 {
            get {
                return ResourceManager.GetString("answer35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-n.
        /// </summary>
        public static string answer36 {
            get {
                return ResourceManager.GetString("answer36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string answer37 {
            get {
                return ResourceManager.GetString("answer37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string answer38 {
            get {
                return ResourceManager.GetString("answer38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string answer39 {
            get {
                return ResourceManager.GetString("answer39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 měsíc.
        /// </summary>
        public static string answer4 {
            get {
                return ResourceManager.GetString("answer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno organizace.
        /// </summary>
        public static string answer40 {
            get {
                return ResourceManager.GetString("answer40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revezní názvy Domen.
        /// </summary>
        public static string answer41 {
            get {
                return ResourceManager.GetString("answer41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaskády zkratek.
        /// </summary>
        public static string answer42 {
            get {
                return ResourceManager.GetString("answer42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globalni učet.
        /// </summary>
        public static string answer43 {
            get {
                return ResourceManager.GetString("answer43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podúčet.
        /// </summary>
        public static string answer44 {
            get {
                return ResourceManager.GetString("answer44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresář.
        /// </summary>
        public static string answer45 {
            get {
                return ResourceManager.GetString("answer45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 rok.
        /// </summary>
        public static string answer5 {
            get {
                return ResourceManager.GetString("answer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 dní.
        /// </summary>
        public static string answer6 {
            get {
                return ResourceManager.GetString("answer6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programové chyby.
        /// </summary>
        public static string answer7 {
            get {
                return ResourceManager.GetString("answer7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nečekané chyby.
        /// </summary>
        public static string answer8 {
            get {
                return ResourceManager.GetString("answer8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Běhové chyby.
        /// </summary>
        public static string answer9 {
            get {
                return ResourceManager.GetString("answer9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dále.
        /// </summary>
        public static string bnext {
            get {
                return ResourceManager.GetString("bnext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odeslat.
        /// </summary>
        public static string bsend {
            get {
                return ResourceManager.GetString("bsend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět.
        /// </summary>
        public static string bzpet {
            get {
                return ResourceManager.GetString("bzpet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souhlasím s podmínkamy zkoušky.
        /// </summary>
        public static string checkbox {
            get {
                return ResourceManager.GetString("checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string heslo {
            get {
                return ResourceManager.GetString("heslo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konec.
        /// </summary>
        public static string konec {
            get {
                return ResourceManager.GetString("konec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konec.
        /// </summary>
        public static string konec3 {
            get {
                return ResourceManager.GetString("konec3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výsledek: .
        /// </summary>
        public static string label111 {
            get {
                return ResourceManager.GetString("label111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nezadali jste správně heslo.
        /// </summary>
        public static string label41 {
            get {
                return ResourceManager.GetString("label41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nezadali jste správně své jméno.
        /// </summary>
        public static string label42 {
            get {
                return ResourceManager.GetString("label42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nezadali jste správně své jméno, heslo nebo jste nesouhlasili s podmínkami..
        /// </summary>
        public static string label43 {
            get {
                return ResourceManager.GetString("label43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesouhlasili jste s podmínkami..
        /// </summary>
        public static string podminka {
            get {
                return ResourceManager.GetString("podminka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otázka: .
        /// </summary>
        public static string pozice {
            get {
                return ResourceManager.GetString("pozice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaký je standardní časový limit kontroly stavu aplikace Cloud Foundry?.
        /// </summary>
        public static string question1 {
            get {
                return ResourceManager.GetString("question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaká je maximální velikost balíčku aplikace při nasazení v systému SAP BTP?.
        /// </summary>
        public static string question10 {
            get {
                return ResourceManager.GetString("question10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaký limit rychlosti požadavků se v systému SAP BTP snaží chránit rozhraní API Cloud Foundry před zneužitím?.
        /// </summary>
        public static string question11 {
            get {
                return ResourceManager.GetString("question11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolik správců lze přiřadit ke globálnímu účtu?.
        /// </summary>
        public static string question12 {
            get {
                return ResourceManager.GetString("question12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaká hodnota chyb je přiřazena záporné kritičnosti?.
        /// </summary>
        public static string question13 {
            get {
                return ResourceManager.GetString("question13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co doporučuje společnost SAP používat pro konstrukci názvů oborů názvů při používání oborů názvů?.
        /// </summary>
        public static string question14 {
            get {
                return ResourceManager.GetString("question14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na jaké úrovni můžete vybrat region?.
        /// </summary>
        public static string question15 {
            get {
                return ResourceManager.GetString("question15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po jaké době GitHub odstraní nepoužívané osobní přístupové tokeny?.
        /// </summary>
        public static string question2 {
            get {
                return ResourceManager.GetString("question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Které typy chyb byste podle osvědčených postupů SAP CAP NEMĚLI zachytit?.
        /// </summary>
        public static string question3 {
            get {
                return ResourceManager.GetString("question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Který vzor použijete pro registraci obsluhy události?.
        /// </summary>
        public static string question4 {
            get {
                return ResourceManager.GetString("question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaké jsou některé vlastnosti souborů YAML?.
        /// </summary>
        public static string question5 {
            get {
                return ResourceManager.GetString("question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Který programovací jazyk je založen na JSON?.
        /// </summary>
        public static string question6 {
            get {
                return ResourceManager.GetString("question6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolik obsluh událostí lze zaregistrovat pro jednu fázi ?.
        /// </summary>
        public static string question7 {
            get {
                return ResourceManager.GetString("question7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaký je maximální počet spuštěných vláken na instanci aplikace?.
        /// </summary>
        public static string question8 {
            get {
                return ResourceManager.GetString("question8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Které klíčové slovo se v systému CAP používá k odesílání událostí?.
        /// </summary>
        public static string question9 {
            get {
                return ResourceManager.GetString("question9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začatek zkošky.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel : .
        /// </summary>
        public static string user_Text {
            get {
                return ResourceManager.GetString("user.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno a příjmení.
        /// </summary>
        public static string uzivatel {
            get {
                return ResourceManager.GetString("uzivatel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vítejte na zkoušce C_CPE_14.
        /// </summary>
        public static string vitej {
            get {
                return ResourceManager.GetString("vitej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začít Test.
        /// </summary>
        public static string zacatek {
            get {
                return ResourceManager.GetString("zacatek", resourceCulture);
            }
        }
    }
}
